version: '3.9'
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    volumes:
      - ./vols/mysql/data/:/var/lib/mysql/
    user: 1000:1000
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - 8001:80